services:
  scanner:
    build: ./scanner
    ports:
      - "8081:8081"

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - SCANNER_URL=http://scanner:8081
      - DB_PATH=/app/data/scans.db
      - API_KEY=${API_KEY}
    depends_on:
      - scanner
    volumes:
      - scan-data:/app/data
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

volumes:
  scan-data: